# ARRAY

In [1]:
import numpy as np

In [2]:
# array given as input
a = [1,2,3,4,5]
b = np.array(a)
print(b)
print(type(b))
print(b.ndim)  # ndim function is used to find the dimension of the array

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [3]:
b

array([1, 2, 3, 4, 5])

In [4]:
#user defined array
l = []

for num in range(4):
    int_1 = int(input("Enter the values: "))
    l.append(int_1)
    
print(np.array(l))

Enter the values: 1
Enter the values: 2
Enter the values: 3
Enter the values: 4
[1 2 3 4]


In [5]:
#2D array creation
ar2 = np.array([[1,2,3,4],[1,2,3,4]])  # number of elements should be same for 2d or more dimension array
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [6]:
# ar2 = np.array([[1,2,3,4],[1,2,3]])  # this gives the error because the number of elements in both the list are not same
# print(ar2)
# print(ar2.ndim)

In [7]:
#3D array creation
ar3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]]) 
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [8]:
#multi dimension array
arn = np.array([1,2,3,4], ndmin = 10)  
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
