In [1]:
import numpy as np

# Array with 0's

In [2]:
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Array with 1's

In [3]:
ar_one = np.ones(4)
ar_one1 = np.ones((3,4))
print(ar_one)
print()
print(ar_one1)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Empty array

In [4]:
ar_em = np.empty(4)

print(ar_em)

[1. 1. 1. 1.]


# Array with range of values

In [5]:
ar_rn = np.arange(4)

print(ar_rn)

[0 1 2 3]


# Array diagonal elements filled with 1's

In [6]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Array with a specified interval

In [7]:
ar_lin = np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]
