In [1]:
import numpy as np

In [2]:
#using the rand() function
var = np.random.rand(4) #it will create a 1D array with 4 values and all the values is between 0 and 1

print(var)

[0.15352663 0.35178503 0.61560189 0.5650219 ]


In [3]:
var1 = np.random.rand(2,5) #it will create a 2D array of 2*5 dimension and all the values is between 0 and 1

print(var1)

[[0.85879476 0.39149014 0.44956356 0.44862189 0.35227778]
 [0.27992268 0.74896627 0.75242803 0.20593406 0.76181909]]


In [4]:
#using the randn() function
varn = np.random.randn(4) #it will create a 1D array with 4 values and all the values are close to 0 and may be -ve also 

print(varn)

[ 0.99479655 -0.02116113 -1.50889861  1.05143908]


In [5]:
varn1 = np.random.randn(3,4) #it will create a 1D array with 3*4 dimension all the values are close to 0 and may be -ve also 

print(varn1)

[[-1.03506054 -0.80304326 -0.26869981  0.57230935]
 [ 0.5487564  -0.93625682  0.39796458 -0.98052088]
 [-1.70856124 -0.27105806  1.1752295   0.05016157]]


In [6]:
#using the ranf() function
varf = np.random.ranf(4) 

print(varf)

[0.49858454 0.8186094  0.67014024 0.49285596]


In [8]:
#using the randint() function
vard = np.random.randint(1,10,5 ) 

print(vard)

[3 9 6 7 4]
