In [1]:
import numpy as np

In [2]:
var = np.array([1,2,3,4])

print("Data type: ", var.dtype)

Data type:  int32


In [3]:
var = np.array([1.0,1.2,1.3,1.4])

print("Data type: ", var.dtype)

Data type:  float64


In [5]:
var = np.array(["a","s","f","d"])

print("Data type: ", var.dtype)

Data type:  <U1


In [6]:
var = np.array(["a","s","f","d",1,2,3,4])

print("Data type: ", var.dtype)

Data type:  <U11


# Data type conversion

In [9]:
x = np.array([1,2,3,4], dtype = np.int8)

print("Data type: ", x.dtype) # now we want to convert this data type from int32 to int8
print(x)

Data type:  int8
[1 2 3 4]


In [10]:
x1 = np.array([1,2,3,4], dtype = "f") # we can use the special characters also to convert the data type of numpy array  
                                        #elements
print("Data type: ", x1.dtype)
print(x1)

Data type:  float32
[1. 2. 3. 4.]


In [14]:
x2 = np.array([1,2,3,4])

new = np.float32(x2)  # this is how we create a function also to convert one data type to another

new_one = np.int32(new)

print("Data type: ", x2.dtype)
print("Data type: ", new.dtype)
print("Data type: ", new_one.dtype)

print(x2)
print(new)
print(new_one)

Data type:  int32
Data type:  float32
Data type:  int32
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [3]:
x3 = np.array([1,2,3,4])

new1 = x3.astype(float) # with the help of astype() function we can convert the data types from one to another

print(x3)
print(new1)
print(x3.dtype)
print(new1.dtype)

[1 2 3 4]
[1. 2. 3. 4.]
int32
float64
