In [1]:
import numpy as np

In [2]:
var = np.array([1,2,3,4])
varadd = var + 3
print(varadd)

[4 5 6 7]


In [3]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd1 = var1 + var2

print(varadd1)

[2 4 6 8]


In [4]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd1 = var1 - var2

print(varadd1)

[0 0 0 0]


In [5]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd1 = var1 * var2

print(varadd1)

[ 1  4  9 16]


In [6]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd1 = var1 / var2

print(varadd1)

[1. 1. 1. 1.]


In [7]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd1 = var1 % var2

print(varadd1)

[0 0 0 0]


In [8]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd1 = var1 ** var2

print(varadd1)

[  1   4  27 256]


In [9]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd1 = np.add(var1, var2)  # performing arthmatic operation using the add() function

print(varadd1)

[2 4 6 8]


In [12]:
#performing arithmatic operations on 2D array
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])

print(var21)
print()
print(var22)
print()
varadd21 = var21 + var22

print(varadd21)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


In [13]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])

print(var21)
print()
print(var22)
print()
varadd21 = var21 * var22

print(varadd21)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[ 1  4  9 16]
 [ 1  4  9 16]]


In [23]:
#some more arithmatic functions on numpy array
var = np.array([1,2,3,4,5,3,2])

print("Minimum value in the array is:",np.min(var), np.argmin(var))
print("Maximum value in the array is:",np.max(var), np.argmax(var))
print("sqrt: ", np.sqrt(var))


Minimum value in the array is: 1 0
Maximum value in the array is: 5 4
sqrt:  [1.         1.41421356 1.73205081 2.         2.23606798 1.73205081
 1.41421356]


In [21]:
var1 = np.array([[2,1,3],[9,5,6]])

print(np.min(var1,axis = 1))  #axis is used to find min, max in 2D array

[1 5]


In [26]:
var2 = np.array([1,2,3])

print(np.sin(var2))
print(np.cos(var2))
print(np.cumsum(var2))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[1 3 6]
