In [1]:
import numpy as np

In [4]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

print(var1 + var2)

[2 4 6 8]


In [7]:
var1 = np.array([1,2,3])
print(var1)
print(var1.shape)
print()

var2 = np.array([[1],[2],[3]])
print(var2)
print(var2.shape)
print()

print(var1+var2)

[1 2 3]
(3,)

[[1]
 [2]
 [3]]
(3, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [13]:
var21 = np.array([[1],[2]])
print(var21)
print(var21.shape)

print()

var23 = np.array([[1,2,3],[1,2,3]])
print(var23)
print(var23.shape)

print()
print(var21 + var23) # this is broadcasting as we get the result array of the dimension 2*3
print((var21 + var23).shape)

[[1]
 [2]]
(2, 1)

[[1 2 3]
 [1 2 3]]
(2, 3)

[[2 3 4]
 [3 4 5]]
(2, 3)
