In [1]:
import numpy as np

# Indexing

In [2]:
var = np.array([9,8,7,6])  # indexing in 1D array starts from 0 and we can get the elements with the help of square brackets

print(var[0])
print(var[-1])  # we can also get the numbers from reverse by using the -ve indexing

9
6


In [3]:
var1 = np.array([[9,8,7],[4,5,6]])

print("The dimension of the array is: ",var1.ndim)
print()
print(var1)
print(var1[1][1])   #this is how we access the elements of 2D array through indexing
print(var1[0][1])

The dimension of the array is:  2

[[9 8 7]
 [4 5 6]]
5
8


In [18]:
var2 = np.array([[[1,2],[6,7]]])

print(var2)
print(var2.ndim)
print()

print(var2[0][1][0])  # this is how we access the elements of 3D array using indexing
print(var2[0][0][1])

[[[1 2]
  [6 7]]]
3

6
2


# Slicing

In [30]:
var = np.array([1,2,3,4,5,6,7])

print(var)
print()

print("2 to 5: ",var[1:5])  # this is the syntax used to do the slicing in 1D arrays
print("2 to end: ", var[1:])
print("start to 5: ", var[:5])

print()

print("Printing using step size of 2: ", var[1:6:2])
print("Printing using step size of 2: ", var[::2])

[1 2 3 4 5 6 7]

2 to 5:  [2 3 4 5]
2 to end:  [2 3 4 5 6 7]
start to 5:  [1 2 3 4 5]

Printing using step size of 2:  [2 4 6]
Printing using step size of 2:  [1 3 5 7]


In [8]:
var1 = np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])

print(var1)
print()
print("8 to 5: ",var1[1,1:])  # this is how we use slicing in 2D arrays
print("8 to 5: ",var1[2,1:])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]

8 to 5:  [8 7 6 5]
8 to 5:  [12 13 14 15]
