In [1]:
import numpy as np

In [3]:
var = np.array([9,8,7,6,5,4])

print(var)
print()

for i in var:  # this is how we iterate in 1D arrays by using 1 for loop
    print(i)

[9 8 7 6 5 4]

9
8
7
6
5
4


In [6]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])

print(var1)
print()

for j in var1:  # this is how we iterate in 2D arrays by using 2 for loop
    for i in j:
        print(i)

[[1 2 3 4]
 [1 2 3 4]]

1
2
3
4
1
2
3
4


In [10]:
var3 = np.array([[[1,2,3],[4,5,6]]])

print(var3)
print()

for i in var3:  # this is how we iterate in 3D arrays by using 3 for loop
    for j in i:
        for k in j:
            print(k)

[[[1 2 3]
  [4 5 6]]]

1
2
3
4
5
6


In [11]:
var3 = np.array([[[1,2,3],[4,5,6]]])

print(var3)
print()

for i in np.nditer(var3):  # we can also iterate the array without using the for-loop again and again with the help of 
                           # the nditer() function
    print(i)

[[[1 2 3]
  [4 5 6]]]

1
2
3
4
5
6


In [2]:
var4 = np.array([[[1,2,3],[4,5,6]]])

print(var4)
print()

for i in np.nditer(var4, flags=['buffered'], op_dtypes=["S"]):  # we can also use many other arguments in the nditer() function also
    print(i)

[[[1 2 3]
  [4 5 6]]]

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'


In [3]:
var4 = np.array([[[1,2,3],[4,5,6]]])

print(var4)
print(var4.ndim)
print(var4.shape)
print()

for i in np.ndenumerate(var4):  # ndenumerate() function is used to get the indexing along with the data
    print(i)

[[[1 2 3]
  [4 5 6]]]
3
(1, 2, 3)

((0, 0, 0), 1)
((0, 0, 1), 2)
((0, 0, 2), 3)
((0, 1, 0), 4)
((0, 1, 1), 5)
((0, 1, 2), 6)
