In [1]:
import numpy as np

In [2]:
var = np.array([1,2,3,4])
var1 = np.array([9,8,7,6])

ar = np.concatenate((var,var1))  #.concatenate() is the function used to merge two arrays to create a single array
print(ar)

[1 2 3 4 9 8 7 6]


In [5]:
vr = np.array([[1,2],[3,4]])
vr1 = np.array([[9,8],[7,6]])

ar_new = np.concatenate((vr,vr1), axis=1)  
print(ar_new)

[[1 2 9 8]
 [3 4 7 6]]


In [11]:
var_1 = np.array([1,2,3,4])
var_2 = np.array([9,8,7,6])

a_new = np.stack((var_1,var_2), axis = 0)  #.stack() is the function used to merge two arrays along the axis
a_new1 = np.hstack((var_1,var_2))  #row
a_new2 = np.vstack((var_1,var_2))  #column
a_new3 = np.dstack((var_1,var_2))  #height
print(a_new)
print()
print(a_new1)
print()
print(a_new2)
print()
print(a_new3)

[[1 2 3 4]
 [9 8 7 6]]

[1 2 3 4 9 8 7 6]

[[1 2 3 4]
 [9 8 7 6]]

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


In [17]:
spl = np.array([1,2,3,4,5,6])

print(spl)
print()

ar = np.array_split(spl,3)
print(ar)
print(ar[0])  # accessing the array from the list

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]


In [21]:
spl1 = np.array([[1,2],[3,4],[5,6]])

print(spl1)
print()

ar1 = np.array_split(spl1,3)
ar2 = np.array_split(spl1,3, axis=1)  # this is how we can split the array along the axis also

print(ar1)
print()
print(ar2)
print()

[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]

