In [1]:
import numpy as np

In [9]:
var = np.array([4,1,2,3,4,2,5,2,5,6,7])

x = np.where(var==2)
x1 = np.where((var%2)==0)

print(x)
print()
print(x1)

(array([2, 5, 7], dtype=int64),)

(array([0, 2, 4, 5, 7, 9], dtype=int64),)


In [12]:
var1 = np.array([1,2,3,4,6,7,8])

x2 = np.searchsorted(var1,5)
x3 = np.searchsorted(var1,5,side="right")
x4 = np.searchsorted(var1,[5,6,7],side="right")  # we can also give the list of elements to be inserted

print(x2)
print(x3)
print(x4)

4
4
[4 5 6]


In [13]:
vr1 = np.array([4,2,5,6,7,9,2,5,3])

xm = np.sort(vr1)

print(xm)

[2 2 3 4 5 5 6 7 9]


In [14]:
vr2 = np.array(['a','d','r','b'])

xm1 = np.sort(vr2)

print(xm1)

['a' 'b' 'd' 'r']


In [15]:
vr3 = np.array([[4,2],[5,6],[7,9],[2,5]])

xm2 = np.sort(vr3)  # we can also sort a 2D array

print(xm2)

[[2 4]
 [5 6]
 [7 9]
 [2 5]]


In [20]:
fil = np.array(["a","s","d","f"])

fil_list = [True, False, True, False]

new_fil = fil[fil_list]

print(new_fil)
print(type(new_fil))

['a' 'd']
<class 'numpy.ndarray'>
