In [1]:
import numpy as np

In [5]:
var = np.array([1,2,3,4,5])

np.random.shuffle(var)

print(var)

[4 1 3 5 2]


In [10]:
var1 = np.array([1,2,3,4,2,3,4,5,1,2,1])

x = np.unique(var1, return_index="true", return_counts="true")

print(x)

(array([1, 2, 3, 4, 5]), array([0, 1, 2, 3, 7], dtype=int64), array([3, 3, 2, 2, 1], dtype=int64))


In [12]:
var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2, (3,2))

print(y)

[[1 2]
 [3 4]
 [5 6]]


In [20]:
var2 = np.array([1,2,3,4,5,6])
y = np.resize(var2, (3,2))
print(y)
print()
print("Flatten:",y.flatten(order="f"))   #here we used flatten function
print()
print("Revel:", np.ravel(y, order="f"))  #here we used to ravel function

[[1 2]
 [3 4]
 [5 6]]

Flatten: [1 3 5 2 4 6]

Revel: [1 3 5 2 4 6]
