In [2]:
import numpy as np

In [2]:
var = np.array([1,2,3,4])

print(var)

print()

v = np.insert(var, (2,4), 7)

print()

print(v)

[1 2 3 4]


[1 2 7 3 4 7]


In [19]:
var_app = np.array([1,2,3,4])

v_app = np.append(var, 6.5)  # we can also insert the value in the numpy array using append function

print(v_app)

[1.  2.  3.  4.  6.5]


In [4]:
var1 = np.array([[1,2,3],[1,2,3]])
print(var1)
print()

v1 = np.insert(var1, 2,[22,23,24], axis=0)

print(v1)

[[1 2 3]
 [1 2 3]]

[[ 1  2  3]
 [ 1  2  3]
 [22 23 24]]


In [21]:
var1_app = np.array([[1,2,3],[1,2,3]])

v1_app = np.append(var1_app, [[22,23,24]], axis=0) # using the append() function to insert the data in 2D array

print(v1_app)

[[ 1  2  3]
 [ 1  2  3]
 [22 23 24]]


In [22]:
var_del = np.array([1,2,3,4])

print(var_del)

d = np.delete(var_del, 2)




[1 2 3 4]
[1 2 4]
