In [1]:
import numpy as np

In [14]:
var = np.matrix([[1,2],[1,2]])  #creation of numpy matrix
var2 = np.matrix([[1,2],[1,2]])
print(var)
print(type(var))
print()
print(var+var2)  #addition of numpy matrix
print()
print(var-var2)  #subtraction of numpy matrix
print()
print(var*var2)
print()
print(var.dot(var2))

[[1 2]
 [1 2]]
<class 'numpy.matrix'>

[[2 4]
 [2 4]]

[[0 0]
 [0 0]]

[[3 6]
 [3 6]]

[[3 6]
 [3 6]]


In [15]:
var1 = np.array([[1,2,3],[1,2,3]])  #creation of numpy array

print(var1)
print(type(var1))
print()
print(var1*var1)

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>

[[1 4 9]
 [1 4 9]]
