In [1]:
import numpy as np

In [9]:
mat = np.matrix([[1,2,3],[4,5,6]])

print(mat)
print()
print(np.transpose(mat))  #using the transpose() function
print()
print(mat.T)  # this is also used to do transpose of the matrix

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [8]:
var2 = np.matrix([[1,2],[3,4]])

print(var2)
print()
print(np.swapaxes(var2,0,1))  # this is how we use swapaxes() function

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [10]:
var3 = np.matrix([[1,2],[3,4]])

print(var3)
print()
print(np.linalg.inv(var2))  #this is how we create inverse matrix

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [16]:
var4 = np.matrix([[1,2],[3,4]])

print(var4)
print()
print(np.linalg.matrix_power(var4,2))  # finding power of matrix with n>0 
print()
print(np.linalg.matrix_power(var4,0))  #finding power of matrix with n=0
print()
print(np.linalg.matrix_power(var4,-2))  #finding power of matrix with n<0

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


In [19]:
var5 = np.matrix([[1,2,3],[3,4,3],[1,2,3]])

print(var5)
print()
print(np.linalg.det(var5))  # this is how we can find determinate or matrix

[[1 2 3]
 [3 4 3]
 [1 2 3]]

0.0
